spring:
  datasource:
    url: jdbc:mysql:///highway2ndround?useUnicode=true&characterEncoding=utf8
    username: root
    password: DRCNET_321
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 50
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      pool-name: hikariCP
  redis:
    host: 127.0.0.1
    password: 12345678
    database: 3
swagger:
  enable: false
