spring:
  datasource:
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 50
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      pool-name: hikariCP
      jdbc-url: jdbc:mysql:///highway_xg?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: DRCNET_321
    url: jdbc:mysql:///highway_xg?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
  redis:
    host: 127.0.0.1
    password: 12345678
    database: 3
drcnet:
  swagger: true
server:
  port: 7080
Local:
  station-id-list: [312,523,524]
  enterprise-code: 3
  relation-cache-key: xg_station_trip_count
  risk-map-cache-key: xg_station_risk_count
  previous_tietou_id: previous_tietou_id_3
  previous_car_id: previous_car_id
  previous_end_month: previous_end_month_3
  scriptPath: /disk1/project/highway/xg/execute.sh
