spring:
  datasource:
    url: jdbc:mysql://localhost:8066/mycatDB?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&rewriteBatchedStatements=true
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 50
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      pool-name: hikariCP
  redis:
    host: 192.168.101.204
    password: 12345678
    database: 3
    timeout: 180s
swagger:
  enable: true
