spring:
  datasource:
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 50
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      pool-name: hikariCP
      jdbc-url: jdbc:mysql://192.168.101.201/highway_yl?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: 123456
    url: jdbc:mysql://192.168.101.201/highway_yl?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
  redis:
    host: 192.168.101.204
    password: 12345678
    database: 3
    timeout: 180s
drcnet:
  swagger: true
server:
  port: 7010
Local:
  station-id-list: [191,195,261,297,313]
  enterprise-code: 2
  relation-cache-key: yilu_station_trip_count
  risk-map-cache-key: yilu_station_risk_count
  previous_tietou_id: previous_tietou_id_2
  previous_car_id: previous_car_id
  previous_end_month: previous_end_month_2
  scriptPath: /disk1/project/highway/yilu/execute.sh
